server:
  port: 8080
  
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/mydatabase
    username: root
    password: 
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    
